### PR TITLE
Added pull_request event

### PR DESCRIPTION
**Pull request by Fraccaman**
This should fix the case where we want to run the CI if a PR is made from a fork.

### CODE REVIEW

**Comment by cwgoes** [comment]
Now it looks like it's running twice, though?

**Comment by Fraccaman** [comment]
It's because drone receives two events from the github webhook, 1 is the creation of the PR and one is the push, so starts two build. I'll check how to run one of the other.

**Comment by cwgoes** [comment]
Yes - we want to run on every push to _this_ repository and on any PR to _this_ repository but not twice.

**Comment by cwgoes** [comment]
@Fraccaman Is this updated to our latest discussions (just on PR, for now)?

**Comment by Fraccaman** [comment]
@cwgoes I still have to do some stuff. I will ping as soon as it is ready :)

**Review by cwgoes — APPROVED** [review]
utACK

**Pull request merged**
