### PR TITLE
Add `handler` and `via` to the frontend language and desugar it later

### PR DESCRIPTION
**Pull request by cyberglot**

### CODE REVIEW

**Review by cwgoes — CHANGES_REQUESTED** [review]
Looks relatively straightforward modulo extensible-data questions, also needs testcases.

**Comment by cyberglot** [comment]
@mariari I want to squash it into two or three commits, lmk if it's ok by you.

**Comment by mariari** [comment]
> @mariari I want to squash it into two or three commits, lmk if it's ok by you.

Fine by me, though note that it gets squashed into master, so it'll only show as 1 commit there.

**Review by cwgoes — APPROVED** [review]
ACK, seems straightforward to me, should see a quick review from @mariari before merge

**Comment by cyberglot** [comment]
Rejected in favour of #722.

**Pull request closed without merging**
