### PR TITLE
Drone CD/CI Update

### PR DESCRIPTION
**Pull request by Fraccaman**

### CODE REVIEW

**Comment by cwgoes** [comment]
Doesn't seem to be working yet, e.g. http://54.247.177.222/heliaxdev/juvix/4/1/5

**Comment by Fraccaman** [comment]
It's failing because the `formatting` step is not passing, but its currently not succeeding also on other branches: http://54.247.177.222/heliaxdev/juvix/5

**Comment by cwgoes** [comment]
Try running `make format` on this branch, then push any changes, see if that fixes it.

**Review by cwgoes — APPROVED** [review]
ACK, thanks! :tada:

**Pull request merged**
